# Use custom format
format = """
$time\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$custom\
$line_break\
$character
"""

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'

[custom.git_mob]
command = 'git mob-print --initials'
format = '[\[$symbol($output)\] ]($style)'
shell = '/bin/bash'
when = 'git config --global git-mob.co-author'
style = 'purple'
ignore_timeout = true

[directory]
truncate_to_repo = false
style = 'yellow'
repo_root_style = 'yellow'
before_repo_root_style = 'dimmed white'

[git_branch]
format = '[\($branch(:$remote_branch)]($style)'
style = 'cyan'

[git_commit]
format = '[$hash]($style) '
only_detached = false
style = 'dimmed white'

[git_status]
format = '( [$all_status$ahead_behind]($style))[\) ]($style)'
stashed = ''
modified = '*'
deleted = "×"
style = 'cyan'

[time]
disabled = false
format = '[$time]($style) '
style = 'green'
