theme = "catppuccin_mocha"

[editor]
cursorline = true
line-number = "relative"
true-color = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
X = "select_line_above"

[keys.select]
X = "select_line_above"
