- name: Install asdf-vm
  tags: [ asdf ]
  git:
    repo: https://github.com/asdf-vm/asdf.git
    depth: 1
    dest: ~/.asdf
    version: v{{ asdf_version }}

- name: Update asdf-vm
  tags: [ asdf ]
  shell: asdf update
