- name: Install delta
  tags: [ delta ]
  become: yes
  apt:
    deb: https://github.com/dandavison/delta/releases/download/{{ delta_version }}/git-delta_{{ delta_version }}_amd64.deb
    state: present
