---
- name: Install n (Node.js version management) with latest version of Node
  tags: [ node ]
  shell: curl -L https://git.io/n-install | PATH=/bin:/usr/bin bash -s -- -y lts
  args:
    creates: ~/n
    executable: /bin/bash
    warn: false

- name: Update n to latest version
  tags: [ node ]
  command: n-update -y

- name: Install latest LTS version of Node
  tags: [ node ]
  command: n lts

- name: Install some npm packages
  tags: [ node, npm ]
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
    executable: ~/n/bin/npm
  with_items:
  - diff-so-fancy
  - serve
  - ngrok
  - npm
  - tldr
  - yarn
