---
- name: Install latest LTS version of Node
  tags: [ node ]
  command: mise use --global node@lts

- name: Enable corepack
  tags: [ node, corepack ]
  command: corepack enable

- name: Install latest pnpm
  tags: [ node, corepack, pnpm ]
  command: corepack prepare pnpm@latest --activate

- name: Install some npm packages
  tags: [ node, npm ]
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
    executable: npm
  with_items:
  - git-mob
  - npm
  - serve
  - ngrok
  - tldr
