---
- name: Always enable corepack with Node
  tags: [ node, corepack ]
  command: mise set --global MISE_NODE_COREPACK=true

- name: Install latest LTS version of Node
  tags: [ node ]
  command: mise use --global node@lts

- name: Install latest pnpm
  tags: [ node, corepack, pnpm ]
  command: corepack prepare pnpm@latest --activate

- name: Update npm to the latest version
  tags: [ node, npm ]
  npm:
    name: npm
    state: latest
    global: yes
    executable: npm

- name: Tell mise to check .node-version
  tags: [ node ]
  command: mise settings add idiomatic_version_file_enable_tools node

- name: Install some npm packages
  tags: [ node, npm ]
  command: "mise use --global npm:{{ item }}@latest"
  register: output
  changed_when:
  - '"installed" in output.stderr'
  with_items:
  - git-mob
  - serve
  - ngrok
  - tldr
