- name: Download yabridge
  tags: [ yabridge ]
  shell: wget https://github.com/robbert-vdh/yabridge/releases/download/{{ yabridge_version }}/yabridge-{{ yabridge_version }}.tar.gz -q -o /dev/null \
    && tar xf yabridge-{{ yabridge_version }}.tar.gz -C $HOME/.local/share
    && rm yabridge-{{ yabridge_version }}.tar.gz

