- name: Install Atuin
  tags: [ atuin ]
  shell: bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
  args:
    creates: /usr/bin/atuin
    executable: /bin/bash
    warn: false

- name: Import existing shell history
  tags: [ atuin ]
  shell: atuin import auto

- name: Generate completions for atuin
  tags: [ atuin ]
  shell: atuin gen-completions --shell bash --out-dir $HOME
