- name: Install Atuin
  tags: [ atuin ]
  shell: bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
  args:
    creates: /usr/bin/atuin
    executable: /bin/bash

- name: Remove line Atuin adds to .bashrc
  tags: [ atuin ]
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: 'eval "$(atuin init bash)"'
    state: absent

- name: Disable up arrow for Atuin
  tags: [ atuin ]
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: 'eval "$(atuin init bash --disable-up-arrow)"'
    state: present

- name: Import existing shell history
  tags: [ atuin ]
  shell: atuin import auto

- name: Generate completions for atuin
  tags: [ atuin ]
  shell: atuin gen-completions --shell bash --out-dir $HOME
