- name: Update apt packages
  tags: [ cypress ]
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install cypress dependencies
  tags: [ cypress ]
  become: yes
  apt:
    state: latest
    pkg:
    # - libgtk2.0-0
    # - libgtk-3-0
    - libgbm-dev
    # - libnotify-dev
    - libgconf-2-4
    # - libnss3
    # - libxss1
    # - libasound2
    # - libxtst6
    # - xauth
    - xvfb

- name: Allow dbus to be sudo started without password prompt
  tags: [ cypress ]
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ ansible_user }}"
    line: "{{ ansible_user }} ALL=(root) NOPASSWD: /etc/init.d/dbus"
    validate: 'visudo -cf %s'

- name: Start dbus with bash
  tags: [ cypress ]
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: 'sudo /etc/init.d/dbus start &> /dev/null'
    state: present
