- name: Install gh (Github tool)
  tags: [ gh ]
  shell: mise use --global gh
  register: output
  changed_when:
  - '"installed" in output.stderr'

- name: Configure gh
  tags: [ gh ]
  shell: gh config set browser browse
