- name: Add Helix PPA repository
  tags: [ helix ]
  become: yes
  apt_repository:
    repo: ppa:maveonair/helix-editor

- name: Install Helix
  tags: [ helix ]
  become: yes
  apt:
    state: latest
    pkg:
    - helix

