- name: Add Helix PPA repository
  tags: [ helix ]
  become: yes
  apt_repository:
    repo: ppa:maveonair/helix-editor

- name: Install Helix
  tags: [ helix ]
  become: yes
  apt:
    state: latest
    pkg:
    - helix

- name: Symlink Helix config file
  tags: [ helix ]
  file:
    src: "~/.dotfiles/helix"
    dest: "~/.config/helix"
    state: link
    force: yes
