- name: Install helix
  tags: [ helix ]
  become: true
  apt:
    deb: https://github.com/helix-editor/helix/releases/download/25.07.1/helix_25.7.1-1_amd64.deb
    state: present

- name: Symlink Helix config file
  tags: [ helix ]
  file:
    src: "~/.dotfiles/helix"
    dest: "~/.config/helix"
    state: link
    force: yes
