- name: Install marker
  tags: [ marker ]
  shell: git clone --depth=1 https://github.com/pindexis/marker ~/.marker && ~/.marker/install.py
  args:
    creates: ~/.marker
    executable: /bin/bash

- name: Remove marker
  tags: [ marker-remove ]
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - ~/.marker
  - ~/.local/share/marker
