- name: Update apt packages
  tags: [ neovim ]
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install neovim
  tags: [ neovim ]
  become: yes
  apt:
    state: latest
    pkg:
    - neovim

- name: Ensure autoload directory exists
  tags: [ neovim ]
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items:
  - ~/.local/share/nvim/site/autoload
  - ~/.config/nvim

- name: Install vim-plug
  tags: [ neovim ]
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    mode: u+x

- name: Symlink config file to dotfiles version
  tags: [ neovim ]
  file:
    src: ~/.dotfiles/nvim
    dest: ~/.config/nvim
    state: link
    force: yes

- name: Use nvim instead of vim
  tags: [ neovim ]
  become: yes
  alternatives:
    name: vim
    path: /usr/bin/nvim
