- name: Install Ruby requirements
  tags: [ ruby ]
  become: yes
  apt:
    cache_valid_time: 3600
    state: latest
    pkg:
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - zlib1g-dev

- name: Install Ruby
  tags: [ ruby ]
  shell: mise use --global ruby@{{ ruby_version }}
  args:
    creates: ~/.local/share/mise/installs/ruby/{{ ruby_version }}
    executable: /bin/bash

- name: Tell mise to check .ruby-version
  tags: [ ruby ]
  command: mise settings add idiomatic_version_file_enable_tools ruby
