- name: Install Ruby requirements
  tags: [ ruby ]
  become: yes
  apt:
    cache_valid_time: 3600
    state: latest
    pkg:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev

- name: Add Ruby plugin to asdf
  tags: [ ruby ]
  shell: ~/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  args:
    creates: ~/.asdf/plugins/ruby
    executable: /bin/bash

- name: Update Ruby plugin
  tags: [ ruby ]
  shell: ~/.asdf/bin/asdf plugin update ruby

- name: Install Ruby
  tags: [ ruby ]
  shell: ~/.asdf/bin/asdf install ruby {{ ruby_version }} && ~/.asdf/bin/asdf global ruby {{ ruby_version }}
  args:
    creates: ~/.asdf/installs/ruby/{{ ruby_version }}
    executable: /bin/bash
