- name: Install Rust
  tags: [ rust ]
  shell: mise use --global rust@{{ rust_version }}
  environment:
    RUST_WITHOUT: rust-docs
  args:
    creates: ~/.local/share/mise/installs/rust/{{ rust_version }}
    executable: /bin/bash
