---
- hosts: localhost
  roles:
    - role: common
      tags: [ common ]
    - role: extra
      tags: [ extra ]
    - role: mint
      tags: [ mint ]
    - role: private
      tags: [ private ]
    - role: uninstall
      tags: [ uninstall ]
  vars:
    home: "{{ ansible_env['HOME'] }}"
    delta_version: 0.18.2
    php_version: 7.4
    ruby_version: 3.2.5
    rust_version: 1.68.0
    vagrant_version: 2.2.10
