---
- hosts: localhost
  roles:
    - role: common
      tags: [ common ]
    - role: extra
      tags: [ extra ]
  vars:
    - home: "{{ ansible_env['HOME'] }}"
    - asdf_version: 0.7.8
    - gh_version: 0.10.1
