---
- hosts: localhost
  roles:
    - role: common
      tags: [ common ]
    - role: extra
      tags: [ extra ]
    - role: private
      tags: [ private ]
  vars:
    - home: "{{ ansible_env['HOME'] }}"
    - asdf_version: 0.8.0
    - gh_version: 1.8.1
    - php_version: 7.4
    - rubocop_version: 0.23.0
    - ruby_version: 2.6.6
    - vagrant_version: 2.2.10
