---
- name: Remove asdf and everything it installed
  tags: [ uninstall-asdf ]
  file:
    path: ~/.asdf
    state: absent

- name: Note about .tool-versions
  debug:
    msg: You can probably also delete ~/.tool-versions now too, but first make sure everything there is managed by mise.
